name: example-start
on: [push]
jobs:
  start:
    # example with web application build,
    # server start and waiting for the server
    # to respond before running tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/start
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:5000'

  start-multiple:
    # example with web application build
    # and several services to start
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/start
          build: npm run build
          # single start command per line
          start: |
            npm start
            npm run start2
          wait-on: 'http://localhost:8000'
          config: 'baseUrl=http://localhost:8000'

  start-multiple-commas:
    # example with web application build
    # and several services to start
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/start
          build: npm run build
          # use commas to separate the commands
          start: npm start, npm run start2
          wait-on: 'http://localhost:8000'
          config: 'baseUrl=http://localhost:8000'
